name: Release Pipeline (master/1.0)

on:
  push:
    branches:
      - prerelease/1.5.1
  pull_request:
    branches:
      # stable/1.0
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: prerelease/1.5.3
    - name: package
      run: |
        yarn && yarn build
        npx lerna exec -- 'cp package.json build/'
        npx lerna exec -- 'cp README.md build/'
        npx lerna exec -- 'cp ../../LICENSE build/'
    - name: publish to npm
      env:
        NPM_KEY: ${{ secrets.NPM_KEY }}
      run: |
        echo "//registry.npmjs.org/:_authToken=${NPM_KEY}" > ~/.npmrc
        echo 'Publishing to npmjs.org.'
        npx lerna exec -- 'cd build && npm publish --access public'
